name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Flutter (Dart >= 3.7.2)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'  # Essa versão tem Dart 3.7.3
          cache: false               # Evita problemas de cache

      - name: Verificar versão do Flutter
        run: flutter --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
