name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Flutter 3.19.6 (Dart 3.7.3)
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.19.6 --depth 1
          echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      - name: Verificar versão do Flutter
        run: flutter --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
