name: Flutter CI com Deploy Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c처digo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # vers찾o Flutter que suporta Dart 3.7.2+

      - name: Verificar vers찾o do Flutter (confirma a vers찾o correta)
        run: flutter --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web release
        run: flutter build web --release

      - name: Deploy no Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
