name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter (Dart >= 3.7.2)
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1
          echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      - name: Check Flutter version
        run: flutter --version

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web
        run: flutter build web --release
